apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-devops-demo
  template:
    metadata:
      labels:
        app: go-devops-demo
    spec:
      containers:
        - name: go-devops-demo
          image: ghcr.io/mohameddenta/go-devops-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080