apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-devops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-devops-demo
  template:
    metadata:
      labels:
        app: go-devops-demo
    spec:
      containers:
        - name: go-devops-demo
          image: ghcr.io/mohameddenta/go-devops-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: go-devops-demo-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: go-devops-demo-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: go-devops-demo-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go-devops-demo-secret
                  key: DB_PASSWORD