apiVersion: v1
kind: Service
metadata:
  name: go-devops-demo-service
spec:
  selector:
    app: go-devops-demo
  ports:
    - port: 80 # Service port
      targetPort: 9090 # Updated to match the new container port
  type: NodePort